    ---
    - name: Create VM on RHV
      hosts: localhost
      connection: local
      gather_facts: false
      vars:
      rhvm_fqdn: p-br-sp-spo-ctp-rhvm-01.rhhi-vivo.com.br
      rhvm_user: admin@internal
      rhvm_cafile: /etc/pki/ovirt-engine/ca.pem
      rhvm_password: vivo123@
        
      pre_tasks:
        - name: Login to oVirt
          ovirt_auth:
            hostname: "{{ rhvm_fqdn }}"
            username: "{{ rhvm_user }}"
            password: "{{ rhvm_password }}"
            ca_file: "{{ rhvm_cafile | default(omit) }}"
          tags:
            - always
      vars:
        datacenter: CTP
        cluster: CTP
        template: cf_template
        vm_name: test-cf01
      tasks:
      - name: Create and run VM from template
        ovirt_vms:
         auth: "{{ ovirt_auth }}"
          name: "{{ vm_name }}"
          template: "{{ template }}"
          cluster: "{{ cluster }}"
          high_availability: true
          state: present
          wait: yes
      post_tasks:
        - name: Logout from oVirt
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
         tags:
           - always
