---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
  - name: Login to oVirt
    ovirt_auth:
      url: https://p-br-sp-spo-ctp-rhvm-01.rhhi-vivo.com.br/ovirt-engine/api
      username: admin@internal
      password: vivo123@
    tags:
      - always
      
  vars:
    datacenter: CTP
    cluster: CTP
    template: cf_template
    vm_name: test-cf02
  
  tasks:
  - name: Create and run VM from template
    ovirt_vms:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      high_availability: true
      state: present
      id: 63fc2107-877e-4791-8455-b925b4f3e905
      cpu_mode: host_passthrough
        - placement_policy: pinned
      wait: yes
      
  
  post_tasks:
  - name: Logout from oVirt
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
    tags:
      - always
